#pragma once

#define DEVICE_ID 0x02
// #define OVERRIDE_EEPROM

#define MIDI_INTERFACE_ID 0x00

#define I2C_CLOCK_SPEED 100000
#define DEBOUNCE_TIME_MICROS 70000

#define DEBUGGING
// #define DEBUGGING_VERBOSE
